#shopify.app.toml
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57df361ae2041a89491c939693021dde"
name = "crud-app"
handle = "crud-app-20"
application_url = "https://crud-app-ya3h.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://crud-app-ya3h.onrender.com/auth/callback",
  "https://crud-app-ya3h.onrender.com/auth/shopify/callback",
  "https://crud-app-ya3h.onrender.com/api/auth/callback"
]

[pos]
embedded = false
